### ISSUE TITLE
AspireSync is not informing who we are via UserAgent, let's do that?

### ISSUE THREAD

**Issue by asirota** [aspirepress/AspireSync#9]
Should the user agent be a AspireSync rather than masking as a web browser?

https://github.com/aspirepress/AspireSync/blob/main/config/autoload/defaults.global.php

**Comment by sarah-savage** [comment]
It's great to tell people who we are but one of the ways they defend against people like us is user agent identification.

**Comment by asirota** [comment]
I don't think we should be hiding -- they'll block at the network level if they really need to... Just an opinion.

**Comment by chuckadams** [comment]
There's another place in the code where we have `headers => ['AspireSync']`.  Or had, it's getting removed in the latest refactor since it didn't make any sense.  I don't think we need to go out of our way to disguise ourselves, but we can blend in with normal traffic: I suggest we set the UA to WordPress, since we're trying to emulate its requests anyway.

**Comment by chuckadams** [comment]
It turns out that grabbing downloads does need a User-Agent, requests without one get a 403, so in the upcoming mega-PR #19, I've gone and boldly identified ourselves as `AspireSync/0.5` in those requests.  

If they're dumb enough to block us by specific UA we can switch to a stealthier mode, but our traffic is really a drop in the bucket, especially now that we're durably caching everything permanently on S3 (my personal wasabi account right now, but we can rclone it instead of re-downloading everything)

**Comment by asirota** [comment]
Go whole hog add the URL: `AspireSync/0.5; https://aspirepress.org`

Nothing to fear but fear itself.
